### ISSUE TITLE
Improving solution file grading

### ISSUE THREAD

**Issue by woojiahao** [git-mastery/git-autograder#12]
The current grading looks like this:

```python
QUESTION_ONE = "What files are missing from Git, but found on your local repository?"
QUESTION_TWO = "What is responsible for the hidden files?"
QUESTION_THREE = "What is the general pattern used to hide the sensitive/ folder?"
QUESTION_FOUR = "What is the pattern used to only show sensitive/names.txt?"

answers = autograder_repo.answers()

question_two = answers.answers.get_by_question(QUESTION_TWO)
if question_two is None:
    raise autograder_repo.wrong_answer(
        [MISSING_QUESTION.format(question=QUESTION_TWO)]
    )
expected_question_two = ".gitignore"
if question_two.answer.strip() != expected_question_two:
    raise autograder_repo.wrong_answer(
        [
            WRONG_ANSWER.format(
                question=QUESTION_TWO,
                reason=WRONG_QUESTION_TWO.format(file=question_two.answer.strip()),
            )
        ]
    )
```

However this is very clunky as an end user since I'm performing the same set of checks over and over again. So we can perhaps keep the processing of questions as simple as possible. Something like:

```python
grader = (
    SolutionGrader()
    .question(
        question="...",
        validation=[
            is_present(),
            is_not_empty(),
            has_exact_value("..."),
        ],
    )
    .question(
        question="...",
        validation=[
            is_present(),
            contains_value("..."),
        ],
    )
)
```

I think the alternative is to use a YAML specification file instead so that we have a clean UI.

```yml
solution:
  question:
    value: ...
    validation:
      present: true
      empty: false
      value: exact
      expected: ...
      type: list
  question:
    value: ...
    validation:
      present: true
      empty: true
      value: contains
      value: ...
```

The key tradeoff here is that because we're using a specification instead of writing code, we might want to add additional checks that might not be represented easily with just using regular code.

I think that strictly from the PoV of iterating over the code, it might be easier if we went for the former instead of the latter
